
services:
  dnn_dev:
    image: dnn_dev
    runtime: nvidia
    build:
      context: .
      args:
        USER_UID: ${HOST_UID:-1000}
        USER_GID: ${HOST_GID:-1000}
      dockerfile: Dockerfile
      target: dnn_dev
      network: "host"
    ports:
      - "8000:8000"
    privileged: true
    network_mode: "host"
    user: artemis
    init: true 
    stdin_open: true 
    tty: true 
    command: bash 
    # working_dir: /home/artemis/DNN 
    environment:
      DISPLAY:
      XAUTHORITY:
      QT_QPA_PLATFORM: xcb
      GDK_BACKEND: x11
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      GNUPLOT_DRIVER_DIR: "/usr/local/libexec/gnuplot/5.4"
    volumes:
      - type: bind
        source: .
        target: /home/artemis/DNN
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ${XAUTHORITY}
        target: ${XAUTHORITY}
      - /var/run/docker.sock:/var/run/docker-host.sock
